[package]
name = "todo-app"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26.0"

env_logger = { version = "0.11.1", default-features = false, features = [
    "auto-color",
    "humantime",
] }
